# Versão do Docker
version: '3.4'

# Serviços
services:
    db:
        image: postgres:13-alpine
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ecommerceapi
        volumes:
            - .:/db/var/lib/postgresql/data
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - 5050:80
